portal/urls.py
from django.urls import path
from django.conf.urls import url,include
from . import views

app_name = 'portal'

urlpatterns = [
path('register/student', views.register,name='student_register'),
path('login/', views.user_login, name='user_login'),
path('register/college', views.register1, name='college_register'),
]

railwayform/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portal/',include('portal.urls'))
]

portal/models.py
from django.db import models
from django.contrib.auth.models import User
from . import choices
# Create your models here.
class College(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key = True)
    name = models.CharField(max_length = 255, blank = False)
    college_code = models.CharField(max_length = 8, blank = False)
    college_address = models.TextField(blank = True, null = True)

class Student(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key = True)
    college_name = models.CharField(max_length = 128)

class Government(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key = True)
    city = models.CharField(max_length = 100,blank = False)
    officer_name = models.CharField(max_length = 128,blank = False)

class Form(models.Model):
    first_name = models.CharField(max_length = 20)
    last_name = models.CharField(max_length = 20)
    from_station = models.CharField(max_length = 20)
    to_station = models.CharField(max_length = 20)
    pass_type = models.CharField(max_length = 10 , choices = choices.PASS_TYPE, default = "SECOND CLASS")
    sap_id = models.CharField(max_length = 11 ,blank = False)
    address = models.CharField(max_length = 255)

portal/forms.py
from django import forms
from .models import Student, College
from django.contrib.auth.models import User

class StudentForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = Student
        fields = ('email', 'college_name',)

class CollegeForm(forms.ModelForm):
    class Meta:
        model = College
        fields = ('name','college_address','college_code')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','password','email')

portal/views.py
from django.shortcuts import render, redirect,reverse
from django.http import HttpResponseRedirect
from .models import User, Student, College, Government
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from .forms import StudentForm, CollegeForm, UserForm
# Create your views here.
def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = StudentForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            registered = True
            return render(request,'portal/login.html',{})

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = StudentForm()

    return render(request,'portal/signup.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})


def register1(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = CollegeForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            profile.save()
            return render(request,'portal/login.html',{})
            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = CollegeForm()

    return render(request,'portal/signup1.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username ,password = password)
        login_user = False
        if user:
            if user.is_active:
                login(request,user)
            else:
                return HttpResponse("Account Not active")
        else:
            login_user = True
            return render(request,'portal/login.html',{'login_user':login_user})

    else:
        return render(request,'portal/login.html',{})

templates/portal/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>

      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300">
      <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">

  </head>
  <body>
<nav class = "navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container_1">
      <ul class = "navbar navbar-nav">

        {% if user.is_authenticated %}

        {% else %}

        {% endif %}
      </ul>
    </div>

</nav>
<div class="container_2">
  {% block body_block %}

  {% endblock%}

</div>
  </body>
</html>

templates/portal/login.html
{% extends "portal/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1 class="heading2">Please Login</h1>
</div>

<div class="login-page">
  <form class="mx-auto" action="{% url 'portal:user_login' %}" method="post">
    {% csrf_token %}
      <label for="username"><b>USERNAME:</b></label>
      <input type="text" name="username" placeholder="username"/>
      <p></p>
      <label for="password"><b>PASSWORD:</b></label>
      <input type="password" name="password" placeholder="password"/>
      <p></p>
      <button type ="submit" class="btn btn-primary">Login</button>
      {% if login_user %}
      <p><b><i>Invalid Credentials</i></b></p>
      {% endif %}
    </form>

  </div>
{% endblock %}

templates/portal/signup.html
{% extends "portal/base.html" %}

{% block body_block %}

<div class="jumbotron">
  {% if register %}
    <centre><h1 class="heading2">Thank You for registering with us!</h1></centre>
  {% else %}
  <h1 class="heading2">Please Register here</h1>
</div>
<p></p>
  <form enctype="multipart/form-data" method="post">
    {{user_form.as_p}}
    {{profile_form.as_p}}
    {% csrf_token %}



<button type="submit"  class="btn btn-primary">Register</button>
  </form>
  {%  endif %}


{% endblock%}

templates/portal/signup1.html
{% extends "portal/base.html" %}

{% block body_block %}

<div class="jumbotron">
  {% if register %}
    <centre><h1 class="heading2">Thank You for registering with us!</h1></centre>
  {% else %}
  <h1 class="heading2">Please Register here</h1>
</div>
<p></p>
  <form enctype="multipart/form-data" method="post">
    {{user_form.as_p}}
  {{profile_form.as_p}}
    {% csrf_token %}



<button type="submit"  class="btn btn-primary">Register</button>
  </form>
  {%  endif %}


{% endblock%}